### ISSUE TITLE
errors without context

### ISSUE THREAD

**Issue by slang800** [jenius/roots#617] opened 2015-02-23 22:07 UTC
![screenshot from 2015-02-23 17 05 36](https://cloud.githubusercontent.com/assets/1049204/6338649/593cc660-bb7e-11e4-94d0-eac36e4abe5d.png)

**Comment by slang800** [comment] 2015-02-23 22:31
Turns out the error pictured above originated from `cli/watch.coffee` (in the `on_error` function). And is something with WordPress/Jetpack
![screenshot from 2015-02-23 17 28 50](https://cloud.githubusercontent.com/assets/1049204/6339092/8ac9cf18-bb81-11e4-92d1-3a10b3d02263.png)

**Comment by jenius** [comment] 2015-04-09 14:00
Is anyone working on a fix for this, or have a reliable set of steps to reproduce it?

**Comment by slang800** [comment] 2015-04-09 14:41
do the error messages come with a stacktrace when you get them?

**Comment by jenius** [comment] 2015-04-09 14:45
I don't understand your reply, it didn't answer either of the questions I asked, and asked another entirely unrelated question that I am unable to answer since I don't 'get them'...

**Comment by slang800** [comment] 2015-04-09 15:00
Surely you have gotten some error message from roots before, right? Because, almost every time I get an error message from roots it comes with no stack trace, and a unicode X symbol.

As for your questions:

1. not really
2. is it not reproducible for you?

**Comment by jenius** [comment] 2015-04-09 16:12
As is the case with any and every issue that you file in any repo, you need to include reproduction steps if you plan on filing the issue and not submitting a fix yourself. This makes it much easier for me to debug rather than having to try to create an error from something.

The issue itself didn't indicate to me that all errors thrown by roots have no stack trace. The title is vague, and the body is just a screenshot of one specific error you have. I know that you know how to file a good clear issue, could you just take another crack at this one? I need:

1. A clear and concise description of the overall issue
2. A set of steps I can take to reproduce the issue

**Closed** 2016-03-18 14:40 UTC
