### ISSUE TITLE
roots watch sometimes "empties" my files

### ISSUE THREAD

**Issue by slang800** [jenius/roots#606] opened 2015-01-28 04:35 UTC
So, I run `roots watch` on my [jade-book](https://github.com/slang800/jade-book) repo (see the roots3 branch for the exact code in the project)...

![image](https://cloud.githubusercontent.com/assets/1049204/5932248/00bd9a3e-a678-11e4-8df9-2f04f71237d6.png)

It starts recompiling repeatedly and doesn't stop until I hit `^C`. I then go back to my editor and notice that most of the files in the project have been changed, including several pngs, svgs, JS files, a CSS file, and an ico. Looking at the diff, the way that those files were changed, was they were now empty - not deleted, but they had no contents. I don't think that any of the styl, coffeescript, or jade files were changed, but I didn't take a screenshot before I reverted them back.

I ran `roots watch` a few more times to make sure it was reproducible, and I was able to recreate the part where it was "recompiling repeatedly" every time. But it seems that it only emptied the files when I let it continue recompiling for ~5 seconds or more (which happened twice).

Then I started writing up this issue, made the roots3 branch that I mentioned earlier, pushed it up, and then went back to recreating the issue and trying to find a pattern... But now, whenever I run it, it behaves totally normally. I have tried switching the master branch back to the state it was in before, re-running roots watch several times, opening various numbers of atom tabs to see if it's a conflict related to file watchers, and cleaning out the public folder. None of those random attempts at recreating the behaviour described above did anything, and I have no idea what caused it or what stopped it.

**Comment by slang800** [comment] 2015-01-28 14:55
Oh, and this was on the first run after updating from roots rc10 to roots 3.0.0

**Comment by jenius** [comment] 2015-01-28 15:12
Since this makes no sense and is not reproducible I think we can close it for now. If anyone else reports it and has a way that we can reproduce, we'll reopen and look into it again.

**Closed by jenius** 2015-01-28 15:12 UTC
Labels: bug
