### ISSUE TITLE
Roots v3.2.x breaks browserify v0.3.2

### ISSUE THREAD

**Issue by hhsnopek** [jenius/roots#654] opened 2015-07-20 00:40 UTC
It seems breaks the roots-browserify (v0.3.2) extension. I can't give an error log because nothing is presented in the terminal as an error. It says it compiles correctly but when the `build.js` is loaded by the browser, the script seems to only load partially and is inconsistent on where it cuts off each time. Reverting to roots v3.1.x solves the problem; wish I could give more details but there aren't anymore to give :disappointed:

**Comment by Leeds-eBooks** [comment] 2015-08-16 18:56
Hi, new roots user, I was looking for something very specific and roots answered to every single part of it so thanks very much.

I'm getting this error too and I thought I would describe my experience in case it helps (although I have no idea how to debug it usefully). I've managed to narrow it down to one very specific group of lines that break browserify when included in one of my modules. Take them out, it works fine, leave them in, the last 30ish lines of `build.js` are transposed to the top of the file. I can paste the lines if you think it might help but there is absolutely nothing special about them. But I guess there must be some combination of characters that is creating a problem somewhere in the process chain.

However, this _only_ happens during `roots watch`, not `roots compile`, so I think it must have to do with #655 

I'd love to help out if you can explain some way I might be able to debug this more usefully. Adding `debug: true` to `app.coffee` doesn't change the output of `roots watch` at all.

Thanks!

**Comment by jenius** [comment] 2015-08-16 23:32
Hi @Leeds-eBooks -- which version of roots are you using right now? If you are on `3.2.x`, try downgrading to `3.1.0` (`npm i roots@3.1.0 -g`), there have been some strange issues with the latest version. If this does not fix the problem, could you drop a little more detail on which lines, or a minimal sample project that can be used to reproduce the problem?

Thanks so much for the thorough report, and looking forward to helping you figure this one out!

**Comment by Leeds-eBooks** [comment] 2015-08-17 13:39
Thanks for the quick response! It fills me with confidence. Been getting to grips with multipass compilation and it's really fantastic – I thought I would have a nightmare trying to get scss to play nicely with postcss but it works perfectly. And `roots-records` is brilliant.

Anyway yep, this bug was with `3.2.x`, and rolling back to `3.1.0` fixed it. In terms of supplying a sample reproduction of the problem I actually don't think I would be able to because it's so weirdly specific. My project was working completely fine on `3.2.x`, until I introduced these lines:

```javascript
.then(userRes => {
    const user = userRes.info || userRes,
          dropin = [];

    if (!user.dob) {
      dropin.push({
        key: "dob",
        placeholder: "date of birth",
        type: "date"
      });
    }
    if (!user.address) {
      dropin.push(...[{
        key: 'address',
        placeholder: 'address',
        type: 'textarea',
        attributes: {
          rows: '2',
          autocapitalize: 'words'
        }
      }, {
        key: 'city',
        placeholder: 'city',
        type: 'text',
        attributes: {
          autocapitalize: 'words'
        }
      }, {
        key: 'postcode',
        placeholder: 'postcode',
        type: 'text',
        attributes: {
          autocapitalize: 'characters'
        }
      }]);
    }

    if (dropin.length) {
      return A.dropin(
        'We need some extra information from you before you can accept the quote:',
        dropin
      ).then(data => ajax.post('url', data, A.getRestid()));
    } else return Promise.resolve();
  })
  .then(() => ajax.get('url', A.getRestid(), cid + '/' + tid))
  .catch(
    message => message && message.toLowerCase().includes('add a credit card'),
    () => ajax.customer.addCard().then(() => ajax.customer.pay(cid, tid))
  )
  .catch(
    errors => errors && errors.toLowerCase().includes('string'),
    errors => supersonic.ui.dialog.confirm(errors, {
      message: 'String?',
      buttonLabels: ['Yes', 'No']
    }).then(i => i === 0 ?
      ajax.customer.addCard().then(() => ajax.customer.pay(cid, tid)) :
      Promise.reject(errors)
    )
  )
  .then(res =>
    res.redirect ? supersonic.app.openURL(res.redirect) : Promise.reject(res)
  ),

preAuth: (from, to, amount, offerId, preAuthorizationId) =>
  ajax.get(
    `url/${from}/${to}/${amount}/${offerId}?${
      _.toQuery({preAuthorizationId})
    }`, A.getRestid()
  )
```

I was able to narrow it down to these exact lines (pasted here with some urls and strings renamed for legal reasons). If I left the `preAuth` method in, the bug happened, if I left the `.then()` function and its contents (which follow on from another method that didn't cause the bug) in, the bug happened. This is obviously es6 code, run through browserify with a babelify transform. I'm sure this won't be helpful as it seems completely arbitrary to me. There are no syntax errors in this chunk. My `app.coffee` browserify settings are:

```coffeescript
browserify(
  files: 'assets/js/main.js'
  out: 'js/build.js'
  transforms: 'babelify'
)
```

Again, this bug only happens with `watch`, not `compile`, so I think it must have to do with the server or related libraries. Any way I can debug the server processes?

**Comment by jenius** [comment] 2015-08-17 14:29
Great, glad this worked. Yeah the bug in `3.2.x` is with the server. As you probably saw here, it's a very confusing bug, I don't entirely understand why or how it's happening. I'm not on a full-time schedule at the moment so I have much less time to work on this, but I will be taking a look today and tomorrow and trying to work this out.

Sorry for the issues, and I'll let you know as soon as we have rolled out a fix to the latest version!

**Comment by Leeds-eBooks** [comment] 2015-08-17 14:42
Thanks man. Like I said if there's any way I can help out I'd be more than happy to spend some time on this.

**Comment by jenius** [comment] 2016-03-18 14:38
should be fixed in v4

**Closed by jenius** 2016-03-18 14:38 UTC
Labels: bug
