### ISSUE TITLE
Watcher fails to work on certain locations under OSX

### ISSUE THREAD

**Issue by Grenzfrei** [jenius/roots#640] opened 2015-05-27 08:15 UTC
I am working with roots on OSX with ejs as an templating engine, and recently the watcher process does compile once, but fails to react to any changes. It seems to occur only under certain filepaths, when i move my project it works again. I have no idea what causes this behaviour, any ideas?

There are also segmentation faults from time to time, don't know what that means...

**Comment by kylemac** [comment] 2015-05-27 13:31
@Grenzfrei does this happen consistently at certain paths? could you share your `app.coffee` configuration too - that might help us debug.

**Comment by Grenzfrei** [comment] 2015-05-27 15:28
Yes, it happens consistently at certain paths, but only after working there for an while. My app.coffe configuration:

	axis         = require 'axis-css'
	autoprefixer = require 'autoprefixer-stylus'
	rupture      = require 'rupture'
	jeet		     = require 'jeet'
	ejs          = require 'ejs'


	module.exports =
		ignores: ['**/layout.*', '**/_*', '.gitignore', '_*', 'readme*', '.DS_Store', 'layout.*', '.git']

		stylus:
			use: [axis(), rupture(), jeet(), autoprefixer()]

		live_reload: true

		open_browser: false

**Comment by jenius** [comment] 2015-06-04 09:32
Could you leave a little more detail about what filepaths this has been happening at? Dig a little deeper, look for patterns, and give us all the info you can. I still can't diagnose the issue from this yet.

**Comment by kylemac** [comment] 2015-07-13 20:31
ping @Grenzfrei. we'd love to help debug a little more - let us know if you're still seeing this

**Comment by Gioni06** [comment] 2015-08-11 08:52
I'm currently having similar issues with roots watch. It compiles once, but fails on file changes. Roots is looking for jade templates in my `css` / `less` folders. It tells me , that my `navigation.less` has an error in line 1. I double checked every reference but i cannot find out why roots thinks that this is an view file.

      [Error: Error: /Users/Jonas/Documents/Development/Github/qsc-airqoo-update/assets/css/_partials/navigation.less:1
        > 1| extends layout-single
          2| 
          3| block meta
          4|   meta(name='description', content='#{config.glossarItem.description}')

      ENOENT, no such file or directory '/Users/Jonas/Documents/Development/Github/qsc-airqoo-update/assets/css/_partials/layout-single.jade']

The `layout-single.jade` is certainly in my views folder and the `navigation.less` has no jade code inside.

Is this behavior related to this issue?

**Comment by jenius** [comment] 2015-08-18 12:35
The issue referenced above is definitely the cause. I'm looking into a fix for this today. Closing this issue to prefer #662 unless the original author can provide more detail!

**Closed by jenius** 2015-08-18 12:35 UTC
