### ISSUE TITLE
Not working on windows 8

### ISSUE THREAD

**Issue by vishu099** [jenius/roots#608] opened 2015-02-05 11:51 UTC
I am running on windows 8 machine. 
I installed NodeJS as well as Python.
I also set the path of GIT in the  environment variables.

I tried installing Roots using "npm install roots -g" but when the installation something like this appears
"npm WARN optional dep failed, continuing fsevents@0.3.0"

and this appears
Roots@3.0.0 
├── rimraf@2.2.8
├── graceful-fs@3.0.5
├── open@0.0.5
├── colors@1.0.3
├── chokidar@0.9.0 (recursive-readdir@0.0.2)
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── lodash@2.4.1
├── mkdirp@0.5.0 (minimist@0.0.8)
├── when@3.7.2
├── argparse@0.1.16 (underscore@1.7.0, underscore.string@2.4.0)
├── minimatch@2.0.1 (brace-expansion@1.1.0)
├── readdirp@1.3.0 (graceful-fs@2.0.3, readable-stream@1.0.33, minimatch@0.2.14)

├── serve-static@1.8.1 (escape-html@1.0.1, utils-merge@1.0.0, parseurl@1.3.0, se
nd@0.11.1)
├── coffee-script@1.8.0 (mkdirp@0.3.5)
├── update-notifier@0.3.0 (is-npm@1.0.0, string-length@1.0.0, chalk@0.5.1, semve
r-diff@2.0.0, latest-version@1.0.0)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, user-home@1.1.1,
osenv@0.1.0, uuid@2.0.1, js-yaml@3.2.5)
├── keen.io@0.1.3 (underscore@1.5.2, superagent@0.21.0)
├── charge@0.0.3 (infestor@0.2.0, colors@0.6.2, anti-matter@0.0.1, minimist@0.1.
0, node-uuid@1.4.2, morgan@1.0.1, alchemist-middleware@0.0.4, hygienist-middlewa
re@0.0.3, compression@1.4.0, publicist-middleware@0.0.1, connect@3.3.4, faye-web
socket@0.7.3, pathologist-middleware@0.0.1, escapist-middleware@0.0.2, lodash.as
sign@2.4.1, lodash.remove@2.4.1, archivist-middleware@0.0.1, update-notifier@0.1
.10, apology-middleware@0.0.4)
├── accord@0.14.3 (indx@0.2.2, convert-source-map@0.4.1, resolve@1.1.0, glob@4.3
.5, fobject@0.0.3, uglify-js@2.4.16, lodash@3.1.0)
├── sprout@0.1.3 (indx@0.2.2, which@1.0.8, osenv@0.1.0, string@2.1.0, ncp@1.0.1,
 ejs@1.0.0, readdirp@1.1.0, inquirer@0.8.0)
├── ship@0.2.3 (indx@0.2.2, mime@1.2.11, minimatch@1.0.0, fstream@1.0.4, optimis
t@0.6.1, file-map@0.0.1, tar@1.0.3, ftp@0.3.8, update-notifier@0.2.2, js-yaml@3.
2.5, github@0.2.1, request@2.53.0, netlify@0.2.1, ssh2@0.3.6, heroku-client@1.5.
0, bitballoon@0.2.1, aws-sdk@2.1.8, inquirer@0.8.0)
└── npm@2.4.1

I am not sure if roots is installed properly or not.

Then when I run this command "roots new example-project" I got an error like this
? Error: Command failed: Too many arguments.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

Potentially unhandled rejection [3] Error: Command failed: Too many arguments.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

  at ChildProcess.exithandler (child_process.js:658:15)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:766:16)
  at Process.ChildProcess._handle.onexit (child_process.js:833:5)

Can somebody guideme how to install roots on windows 8

**Comment by jenius** [comment] 2015-02-05 14:10
Duplicate of #588

**Closed by jenius** 2015-02-05 14:10 UTC
